version: '3.11'

services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./stripe_payment/.env
    ports:
      - "5432:5432"

  stripe:
    build: ./stripe_payment
    restart: always
    entrypoint: sh entrypoint.sh
    volumes:
      - static_value:/stripe/static/
      - media_value:/stripe/media/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db
      - stripe

volumes:
  postgres_data:
  static_value:
  media_value: